DROP DATABASE IF EXISTS progetto_quinta;

CREATE DATABASE progetto_quinta;

USE progetto_quinta;

CREATE TABLE IF NOT EXISTS gestore(
    id INT NOT NULL AUTO_INCREMENT,
    nome VARCHAR(255) NOT NULL,
    cognome VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,
    ruolo INT NOT NULL,
    PRIMARY KEY(id)
);

CREATE TABLE IF NOT EXISTS azienda(
    id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS dipendente (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR(255) NOT NULL,
    cognome VARCHAR(255) NOT NULL,
    cf VARCHAR(16) UNIQUE NOT NULL,
    data_di_nascita DATE NOT NULL,
    id_azienda INT UNSIGNED
);


CREATE TABLE IF NOT EXISTS ferie(
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    id_dipendente INT UNSIGNED NOT NULL,
    data_inizio DATE NOT NULL,
    data_fine DATE NOT NULL,
    giorni INT UNSIGNED NOT NULL
);

CREATE TABLE IF NOT EXISTS malattia(
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    id_dipendente INT UNSIGNED NOT NULL,
    numero_malattia VARCHAR(9) NOT NULL,
    data_inizio DATE NOT NULL,
    data_fine DATE NOT NULL,
    giorni INT UNSIGNED NOT NULL
);

CREATE TABLE IF NOT EXISTS permesso(
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    id_dipendente INT UNSIGNED NOT NULL,
    data DATE NOT NULL,
    ora_inizio TIME NOT NULL,
    ora_fine TIME NOT NULL
);